spring:
  profiles: api
  http:
    multipart:
      max-request-size: 10MB
      max-file-size: 20MB

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/javascript,application/javascript,text/css


jwtConfig:
  issuer: I-ON
  secretKey: dkdldhs!@#$
  tokenPrefix: SDP
  headString: X-Authorization
  tokenExpirationTime: 1800 #분
  refreshTokenExpTime: 1800 #분


cluster:
  mode: api
  groups: api
  members:
    - 127.0.0.1

infinispan:
  cachePath: /resource/ice2/api

tomcat:
  access-log-enabled: true
  access-log-pattern: "%h %l %u %t \"%r\" %s %b %D"
  basedir: tomcat

logging:
  config:
    classpath:
      - logback-access-dev-2.xml
      - logback-dev-2.xml


file:
  default:
    path: /resource/ice2/files


i18n:
  defaults: en
