# YTN 개발 서버
spring:
  profiles: ytn-stg
  http:
    multipart:
      max-request-size: 20MB
      max-file-size: 1024MB
    mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
  resources:
    chain:
      cache: true
      enabled: true
    cache-period: 3600

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
  tomcat:
    uri-encoding: UTF-8



jwtConfig:
  issuer: I-ON
  secretKey: dkdldhs!@#$
  tokenPrefix: SDP
  headString: X-Authorization
  tokenExpirationTime: 60 #분
  refreshTokenExpTime: 1800 #분

cluster:
  api-prefix: http://tapi.ygoon.com/
  front-prefix: http://test.ygoon.com/
  file-prefix: http://tfile.ygoon.com/
  mode: all
  groups: all
  members:
    - 172.16.0.11

infinispan:
  cachePath: /resource/ice2/cache

tomcat:
  access-log-enabled: true
  access-log-pattern: "%h %l %u %t \"%r\" %s %b %D"
  basedir: tomcat

logging:
  config:
    classpath:
      - logback-access-dev-2.xml
      - logback-dev-2.xml

file:
  default:
    path: /resource/ice2/files

sweettracker:
  tracking-api: https://dev-tracking-api.sweettracker.net/add_invoice
  tier: ytn
  key: LaTfL9LcqSZKG6maH6OPhQ
  callbackUrl: http://tapi.ygoon.com/node/orderDeliveryPrice/event/sweettrackerGetData

openApiNaver:
  clientId: ZzXcURj8oZ8TWy4IM17z
  clientSecret: 6I_U6blJNX