spring:
  profiles: cj-dev
  http:
    multipart:
      max-request-size: 10MB
      max-file-size: 20MB

server:
  port: 8080
jwtConfig:
  issuer: I-ON
  secretKey: dkdldhs!@#$
  tokenPrefix: SDP
  headString: X-Authorization
  tokenExpirationTime: 15 #분
  refreshTokenExpTime: 60 #분

#tomcat:
#  access-log-enabled: true
#  access-log-pattern: "%h %l %u %t \"%r\" %s %b %D"
#  basedir: tomcat

logging:
  config:
    classpath:
      - logback.xml

cluster:
  mode: all
  groups: all
  members:
    - 125.131.88.147
    - 127.0.0.1
    - localhost

infinispan:
  cachePath: /resource/ice2/cache

file:
  default:
    path: /resource/ice2/files


i18n:
  defaults: eng

cjapi:
  pip:
    programurl: http://pipapi.itvs.cjenm.com/json/data/v1.0/global/programinfo.asp
    clipmediaurl: http://pipapi.itvs.cjenm.com/json/data/v1.0/global/clipmediainfo.asp

aws:
  s3:
    bucketName: cjmwave-dev
    bucketKey: ion
    accessKey: AKIAIBQJZKS334ELQ7KA
    secretKey: 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

temp-file:
  dir: /

image:
  prefixUrl: http://125.131.88.147:8080/image/
  s3PrefixUrl: https://cjmwave-dev.s3.ap-northeast-2.amazonaws.com/ion/

mobile:
  push:
    fcmApiKey: AAAA-z1uhx4:APA91bHlHSqGakLe7RKY1fuvTpUyx1hZKX5BG7ydfK96Kfy9bCX0upciPQ6UlpOXECEcc4tsYFiiEUy6aHSWWMZwwN-V6rtu-aeOAGg0_r6GAFaVkJF3jEOxiO4kblsi4tNDOAApMZx2
    fcmApiUrl: https://fcm.googleapis.com/fcm/send