# 기존의 application-aws-apicache 를 대체함
# hazelcast 관련 group 과 mode 를 변경하였음

spring:
  profiles: aws-cache
  http:
    multipart:
      max-request-size: 10MB
      max-file-size: 20MB

server:
  port: 8080

jwtConfig:
  issuer: I-ON
  secretKey: dkdldhs!@#$
  tokenPrefix: SDP
  headString: X-Authorization
  tokenExpirationTime: 15 #분
  refreshTokenExpTime: 60 #분


cluster:
  mode: cache
  groups: cms
  members:
    - 10.75.6.144-145 # CACHE 1-2
    #- 10.75.7.144-145 # CACHE 3
    - 127.0.0.1
    - localhost

infinispan:
  cachePath: /data/ion/api/resource/ice2/cache

tomcat:
  access-log-enabled: true
  access-log-pattern: "%h %l %u %t \"%r\" %s %b %D"
  basedir: tomcat

logging:
  config:
    classpath:
      - logback-access-dev-2.xml
      - logback-dev-2.xml

file:
  default:
    path: /data/ion/api/resource/ice2/files


i18n:
  defaults: eng

cjapi:
  pip:
    programurl: http://pipapi.itvs.cjenm.com/json/data/v1.0/global/programinfo.asp
    clipmediaurl: http://pipapi.itvs.cjenm.com/json/data/v1.0/global/clipmediainfo.asp

aws:
  s3:
    bucketName: cjmwave-prd
    bucketKey: ion
    accessKey: AKIAJWGJBWJU3TLXANWA
    secretKey: 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



temp-file:
  dir: /data/ion/api/resource/ice2/cache
