# Override the default Tomcat port of 8080 to "0", meaning
# pick any available port.
# This is necessary to be able to run multiple copies of the
# application on the same machine.
spring:
  profiles:
    active: dev
  http:
    multipart:
      max-request-size: 10MB
      max-file-size: 20MB
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  resources:
    chain:
      cache: true
      enabled: true
    cache-period: 3600

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/javascript,application/javascript,text/css
  tomcat:
    uri-encoding: UTF-8


jwtConfig:
  issuer: I-ON
  secretKey: dkdldhs!@#$
  tokenPrefix: SDP
  headString: X-Authorization
  tokenExpirationTime: 1800 #분
  refreshTokenExpTime: 1800 #분

cluster:
  api-prefix: http://localhost:8080/
  front-prefix: http://localhost:3090/
  mode: all
  groups: all
  members:
    - 127.0.0.1

infinispan:
  cachePath: /resource/ice2/cache

tomcat:
  access-log-enabled: true
  access-log-pattern: "%h %l %u %t \"%r\" %s %b %D"
  basedir: tomcat


logging:
  config:
    classpath:
      - logback-access-dev-2.xml
      - logback-dev-2.xml


file:
  default:
    path: /resource/ice2/files


i18n:
  defaults: en

temp-file:
  dir: /
---
#-Dspring.profiles.active=dev
spring:
  profiles: dev
logging:
  config: classpath:logback-dev.xml

hazelcast:
  baseDir: /resource/ice2/data_1
  members:
    - 127.0.0.1

temp-file:
  dir: /


---
#-Dspring.profiles.active=dev-2
spring:
  profiles: dev-2
server:
  port: 8090

logging:
  config: classpath:logback-dev-2.xml

session:
  mode: client
  baseDir: /resource/ice2/client
  members:
    - 127.0.0.1


hazelcast:
  baseDir: /resource/ice2/data_2

---
# 교보 개발 서버
spring:
  profiles: kybo-dev
  http:
    multipart:
      max-request-size: 10MB
      max-file-size: 20MB

server:
  port: 8088

jwtConfig:
  issuer: I-ON
  secretKey: dkdldhs!@#$
  tokenPrefix: SDP
  headString: X-Authorization
  tokenExpirationTime: 15 #분
  refreshTokenExpTime: 60 #분


cluster:
  members:
    - 127.0.0.1
    - localhost

infinispan:
  cachePath: /resource/ice2/cache

tomcat:
  access-log-enabled: true
  access-log-pattern: "%h %l %u %t \"%r\" %s %b %D"
  basedir: tomcat

logging:
  config:
    classpath:
      - logback-access-dev-2.xml
      - logback-dev-2.xml


file:
  default:
    path: /resource/ice2/files

temp-file:
  dir: /