spring:
  profiles: multigw
  http:
    multipart:
      max-request-size: 10MB
      max-file-size: 20MB

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/javascript,application/javascript,text/css
  tomcat:
    max-threads: 8000


jwtConfig:
  issuer: I-ON
  secretKey: dkdldhs!@#$
  tokenPrefix: SDP
  headString: X-Authorization
  tokenExpirationTime: 15 #분
  refreshTokenExpTime: 60 #분

# Check IP - 10.75.6.140,10.75.7.140
cluster:
  mode: api
  groups: api
  dataQueue: 10.75.6.140,10.75.7.140
  dataQueueDs: authDb
  map: mbrVoteMap,ipVoteCnt
  members:
    - 10.75.6.131
    - 10.75.7.130
    - 10.75.7.140
    - 10.75.6.140
    - 10.75.7.144
    - 10.75.6.144
    - 10.75.7.150-164
    - 10.75.6.150-164

infinispan:
  cachePath: /data/resource/ice2/cache

tomcat:
  access-log-enabled: true
  access-log-pattern: "%h %l %u %t \"%r\" %s %b %D"
  basedir: tomcat

logging:
  config:
    classpath:
      - logback-cj.xml

file:
  default:
    path: /data/resource/ice2/files

temp-file:
  dir: /data/resource/ice2/cache

i18n:
  defaults: eng

cjapi:
  pip:
    programurl: http://pipapi.itvs.cjenm.com/json/data/v1.0/global/programinfo.asp
    clipmediaurl: http://pipapi.itvs.cjenm.com/json/data/v1.0/global/clipmediainfo.asp

aws:
  s3:
    bucketName: cjmwave-prd
    bucketKey: ion
    accessKey: AKIAJWGJBWJU3TLXANWA
    secretKey: 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

image:
  prefixUrl: http://g-p-api-elb-321213426.ap-northeast-2.elb.amazonaws.com/image/
  s3PrefixUrl: https://cmsimg.mwave.me/

mobile:
  push:
    fcmApiKey: AAAA-z1uhx4:APA91bHlHSqGakLe7RKY1fuvTpUyx1hZKX5BG7ydfK96Kfy9bCX0upciPQ6UlpOXECEcc4tsYFiiEUy6aHSWWMZwwN-V6rtu-aeOAGg0_r6GAFaVkJF3jEOxiO4kblsi4tNDOAApMZx2
    fcmApiUrl: https://fcm.googleapis.com/fcm/send