spring:
  profiles: test
  http:
    multipart:
      max-request-size: 10MB
      max-file-size: 20MB

server:
  port: 9090

jwtConfig:
  issuer: I-ON
  secretKey: dkdldhs!@#$
  tokenPrefix: SDP
  headString: X-Authorization
  tokenExpirationTime: 15 #분
  refreshTokenExpTime: 60 #분

cluster:
  mode: all
  groups: all
  members:
    - 127.0.0.1
    - localhost

infinispan:
  cachePath: /resource/ice2/test

tomcat:
  access-log-enabled: true
  access-log-pattern: "%h %l %u %t \"%r\" %s %b %D"
  basedir: tomcat

logging:
  config:
    classpath:
      - logback-access-dev-2.xml
      - logback-dev-2.xml


file:
  default:
    path: /resource/ice2_test/files


i18n:
  defaults: eng

temp-file:
  dir: /