# 파일명 - boot profile 명 매칭
# schedule-id : (필수) 유일한 스케쥴러 구분값
# execute-class : (필수) 메소드를 실행할 클래스
# execute-method : (필수) Timer 의  run  에서 실행될 메소드
# cron-expression :  (필수) 기존  schedule.properties  와 동일한 규칙 
schedulers:

  - schedule-id: schedulerA
    execute-class: net.ion.ice.service.TestSchedulerService
    execute-method: doA
    cron-expression: 10000

  - schedule-id: schedulerB
    execute-class: net.ion.ice.service.TestSchedulerService
    execute-method: doB
    cron-expression: 60000